Update debug.yml

diff --git a/.github/workflows/debug.yml b/.github/workflows/debug.yml
--- a/.github/workflows/debug.yml
+++ b/.github/workflows/debug.yml
@@ -280,28 +280,74 @@ jobs:
           echo "==> Source: repo file: configs/$CHOICE"
           cp "configs/$CHOICE" "$CONFIG_OUT"
         elif [[ "$CHOICE" =~ ^(default|allyesconfig|allmodconfig|allnoconfig|tinyconfig)$ ]]; then
-          echo "==> Source: kernel built-in target: make $CHOICE"
+          KMAKE_TARGET="$CHOICE"
+          [ "$CHOICE" = "default" ] && KMAKE_TARGET="defconfig"
+          echo "==> Source: kernel built-in target: make $KMAKE_TARGET"
           cd kernel-source
-          make ARCH="$KARCH" "$CHOICE"
+          make ARCH="$KARCH" "$KMAKE_TARGET"
           cp .config "$CONFIG_OUT"
           cd ..
         else
           case "$CHOICE" in
-            alma)     URL='https://git.almalinux.org/rpms/kernel/-/raw/c9/f/kernel-x86_64-fedora.config' ;;
-            alpine)   URL='https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/main/linux-lts/config-lts.x86_64' ;;
-            arch)     URL='https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/raw/main/config' ;;
-            centos)   URL='https://gitlab.com/redhat/centos-stream/rpms/kernel/-/raw/c9s/f/kernel-x86_64-fedora.config' ;;
+            alma)
+              case "$KARCH" in
+                x86_64) URL='https://git.almalinux.org/rpms/kernel/-/raw/c9/f/kernel-x86_64-fedora.config' ;;
+                arm64)  URL='https://git.almalinux.org/rpms/kernel/-/raw/c9/f/kernel-aarch64-fedora.config' ;;
+              esac ;;
+            alpine)
+              case "$KARCH" in
+                x86_64) URL='https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/main/linux-lts/config-lts.x86_64' ;;
+                arm64)  URL='https://gitlab.alpinelinux.org/alpine/aports/-/raw/master/main/linux-lts/config-lts.aarch64' ;;
+              esac ;;
+            arch)
+              case "$KARCH" in
+                x86_64) URL='https://gitlab.archlinux.org/archlinux/packaging/packages/linux/-/raw/main/config' ;;
+                arm64)  URL='https://raw.githubusercontent.com/archlinuxarm/PKGBUILDs/master/core/linux-aarch64/config' ;;
+              esac ;;
+            centos)
+              case "$KARCH" in
+                x86_64) URL='https://gitlab.com/redhat/centos-stream/rpms/kernel/-/raw/c9s/f/kernel-x86_64-fedora.config' ;;
+                arm64)  URL='https://gitlab.com/redhat/centos-stream/rpms/kernel/-/raw/c9s/f/kernel-aarch64-fedora.config' ;;
+              esac ;;
             debian)   URL='https://salsa.debian.org/kernel-team/linux/-/raw/debian/latest/debian/config/config' ;;
-            fedora)   URL='https://src.fedoraproject.org/rpms/kernel/raw/rawhide/f/kernel-x86_64-fedora.config' ;;
+            fedora)
+              case "$KARCH" in
+                x86_64) URL='https://src.fedoraproject.org/rpms/kernel/raw/rawhide/f/kernel-x86_64-fedora.config' ;;
+                arm64)  URL='https://src.fedoraproject.org/rpms/kernel/raw/rawhide/f/kernel-aarch64-fedora.config' ;;
+              esac ;;
             gentoo)   URL='https://gitweb.gentoo.org/proj/gentoo-kernel.git/plain/default_config' ;;
             kali)     URL='https://gitlab.com/kalilinux/packages/linux/-/raw/kali/master/debian/config/config' ;;
-            manjaro)  URL='https://gitlab.manjaro.org/packages/core/linux/-/raw/master/config' ;;
+            manjaro)
+              case "$KARCH" in
+                x86_64) URL='https://gitlab.manjaro.org/packages/core/linux/-/raw/master/config' ;;
+                *) echo "ERROR: manjaro 没有 $KARCH 版本配置" >&2; exit 1 ;;
+              esac ;;
             nixos)    URL='https://raw.githubusercontent.com/NixOS/nixpkgs/master/pkgs/os-specific/linux/kernel/common-config.nix' ;;
-            opensuse) URL='https://raw.githubusercontent.com/openSUSE/kernel-source/master/config/x86_64/default' ;;
-            rhel)     URL='https://gitlab.com/redhat/centos-stream/rpms/kernel/-/raw/c9s/f/kernel-x86_64-fedora.config' ;;
-            rocky)    URL='https://git.rockylinux.org/rocky/kernel/-/raw/r9/f/kernel-x86_64-fedora.config' ;;
-            ubuntu)   URL='https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/plain/debian.master/config/amd64/config.flavour.generic' ;;
-            void)     URL='https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/linux/files/x86_64-dotconfig' ;;
+            opensuse)
+              case "$KARCH" in
+                x86_64) URL='https://raw.githubusercontent.com/openSUSE/kernel-source/master/config/x86_64/default' ;;
+                arm64)  URL='https://raw.githubusercontent.com/openSUSE/kernel-source/master/config/aarch64/default' ;;
+              esac ;;
+            rhel)
+              case "$KARCH" in
+                x86_64) URL='https://gitlab.com/redhat/centos-stream/rpms/kernel/-/raw/c9s/f/kernel-x86_64-fedora.config' ;;
+                arm64)  URL='https://gitlab.com/redhat/centos-stream/rpms/kernel/-/raw/c9s/f/kernel-aarch64-fedora.config' ;;
+              esac ;;
+            rocky)
+              case "$KARCH" in
+                x86_64) URL='https://git.rockylinux.org/rocky/kernel/-/raw/r9/f/kernel-x86_64-fedora.config' ;;
+                arm64)  URL='https://git.rockylinux.org/rocky/kernel/-/raw/r9/f/kernel-aarch64-fedora.config' ;;
+              esac ;;
+            ubuntu)
+              case "$KARCH" in
+                x86_64) URL='https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/plain/debian.master/config/amd64/config.flavour.generic' ;;
+                arm64)  URL='https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/plain/debian.master/config/arm64/config.flavour.generic' ;;
+              esac ;;
+            void)
+              case "$KARCH" in
+                x86_64) URL='https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/linux/files/x86_64-dotconfig' ;;
+                arm64)  URL='https://raw.githubusercontent.com/void-linux/void-packages/master/srcpkgs/linux/files/aarch64-dotconfig' ;;
+              esac ;;
             *) echo "Unknown config_choice: $CHOICE" >&2; exit 1 ;;
           esac
           echo "==> Source: distro '$CHOICE' -> $URL"
